from __future__ import annotations

import json
import shutil
from dataclasses import asdict
from pathlib import Path
from typing import Any

import pandas as pd

from common.paths import runtime_path
from contracts.backtest import ExternalSimulationPackage, ExternalSimulationRequest, ExternalSimulationResult, PerformanceMetrics


SUPPORTED_EXTERNAL_ENGINES = {"gm", "ptrade", "qmt"}


def _template(engine: str) -> str:
    if engine == "gm":
        return '''"""GM import script generated by AgentMatrix.

Import this file in the GM terminal and keep signals.csv in the same folder.
"""
from pathlib import Path
import pandas as pd


SIGNAL_PATH = Path(__file__).with_name("signals.csv")


def init(context):
    context.signals = pd.read_csv(SIGNAL_PATH)
    context.previous_target_codes = set()


def algo(context):
    today = context.now.strftime("%Y-%m-%d")
    targets = context.signals[context.signals["date"] == today]
    current_codes = set(targets["code"].astype(str))
    for symbol in context.previous_target_codes - current_codes:
        order_target_percent(symbol=symbol, percent=0.0)
    for row in targets.itertuples(index=False):
        order_target_percent(symbol=row.code, percent=float(row.target_weight))
    context.previous_target_codes = current_codes
'''
    if engine == "ptrade":
        return '''"""PTrade import script generated by AgentMatrix.

Place signals.csv next to this script and import it into the PTrade research terminal.
"""
from pathlib import Path
import pandas as pd


SIGNAL_PATH = Path(__file__).with_name("signals.csv")


def initialize(context):
    g.signals = pd.read_csv(SIGNAL_PATH)
    g.previous_target_codes = set()


def handle_data(context, data):
    today = context.current_dt.strftime("%Y-%m-%d")
    targets = g.signals[g.signals["date"] == today]
    current_codes = set(targets["code"].astype(str))
    for symbol in g.previous_target_codes - current_codes:
        order_target_percent(symbol, 0.0)
    for row in targets.itertuples(index=False):
        order_target_percent(row.code, float(row.target_weight))
    g.previous_target_codes = current_codes
'''
    if engine == "qmt":
        return '''"""QMT mini strategy script generated by AgentMatrix.

Use signals.csv as the target-position input and map order functions to the
local QMT account wrapper before simulation or live use.
"""
from pathlib import Path
import pandas as pd


SIGNAL_PATH = Path(__file__).with_name("signals.csv")


def init(context):
    context.signals = pd.read_csv(SIGNAL_PATH)
    context.previous_target_codes = set()


def handlebar(context):
    today = context.get_trading_date()
    targets = context.signals[context.signals["date"] == today]
    current_codes = set(targets["code"].astype(str))
    for symbol in context.previous_target_codes - current_codes:
        order_target_percent(symbol, 0.0)
    for row in targets.itertuples(index=False):
        # Bind this call to the local QMT target-percent helper.
        order_target_percent(row.code, float(row.target_weight))
    context.previous_target_codes = current_codes
'''
    raise ValueError(f"Unsupported external simulation engine: {engine}")


def _checklist(engine: str) -> list[str]:
    return [
        "Verify the signal CSV date range, symbol format, and target weights before import.",
        "Run in simulation/paper mode first; do not bind live accounts to generated scripts.",
        "Set commission, slippage, benchmark, and rebalance schedule to match the internal validation assumptions.",
        f"Import strategy_{engine}.py and signals.csv into the {engine} terminal.",
        "Export the terminal simulation result and parse it back into AgentMatrix before promotion.",
    ]


def package_external_simulation(
    request: ExternalSimulationRequest,
    *,
    output_dir: str | Path | None = None,
) -> ExternalSimulationPackage:
    engine = request.engine.lower()
    if engine not in SUPPORTED_EXTERNAL_ENGINES:
        raise ValueError(f"Unsupported external simulation engine: {engine}")
    signal_path = Path(request.signal_path)
    if not signal_path.exists():
        raise FileNotFoundError(f"Signal file not found: {signal_path}")
    signals = pd.read_csv(signal_path)

    package_dir = Path(output_dir) if output_dir else runtime_path("external_sim", request.run_id, engine)
    package_dir.mkdir(parents=True, exist_ok=True)
    copied_signal_path = package_dir / "signals.csv"
    shutil.copyfile(signal_path, copied_signal_path)

    script_path = package_dir / f"strategy_{engine}.py"
    config_path = package_dir / "simulation_config.json"
    checklist_path = package_dir / "import_checklist.md"
    script_path.write_text(_template(engine), encoding="utf-8")
    config_path.write_text(json.dumps(asdict(request), ensure_ascii=False, indent=2), encoding="utf-8")
    checklist = _checklist(engine)
    checklist_path.write_text("\n".join(f"- {item}" for item in checklist) + "\n", encoding="utf-8")

    return ExternalSimulationPackage(
        request=request,
        status="external_sim_ready",
        package_dir=str(package_dir),
        artifacts={
            "signals": str(copied_signal_path),
            "strategy_script": str(script_path),
            "config": str(config_path),
            "checklist": str(checklist_path),
        },
        checklist=checklist,
        diagnostics={
            "engine": engine,
            "signal_rows": int(len(signals)),
            "signal_start": str(signals["date"].min()) if "date" in signals.columns and not signals.empty else "",
            "signal_end": str(signals["date"].max()) if "date" in signals.columns and not signals.empty else "",
            "signal_dates": int(signals["date"].nunique()) if "date" in signals.columns else 0,
        },
    )


def parse_external_simulation_result(
    *,
    run_id: str,
    engine: str,
    result_path: str | Path,
) -> ExternalSimulationResult:
    path = Path(result_path)
    if not path.exists():
        raise FileNotFoundError(f"External simulation result not found: {path}")
    if path.suffix.lower() == ".json":
        payload = json.loads(path.read_text(encoding="utf-8"))
    else:
        frame = pd.read_csv(path)
        if {"metric", "value"}.issubset(frame.columns):
            payload = dict(zip(frame["metric"], frame["value"]))
        elif not frame.empty:
            payload = frame.iloc[-1].to_dict()
        else:
            payload = {}
    metrics = PerformanceMetrics(
        total_return=float(payload.get("total_return", 0.0)),
        annualized_return=float(payload.get("annualized_return", payload.get("annual_return", 0.0))),
        benchmark_return=float(payload.get("benchmark_return", 0.0)),
        excess_return=float(payload.get("excess_return", 0.0)),
        max_drawdown=float(payload.get("max_drawdown", 0.0)),
        sharpe=float(payload.get("sharpe", 0.0)),
        volatility=float(payload.get("volatility", 0.0)),
        turnover=float(payload.get("turnover", 0.0)),
        win_rate=float(payload.get("win_rate", 0.0)),
    )
    return ExternalSimulationResult(
        run_id=run_id,
        engine=engine,
        status="external_sim_passed",
        metrics=metrics,
        source_path=str(path),
        diagnostics={"raw": payload},
    )
